[package]
name = "wasm-quickjs"
version = "0.1.0"
authors = ["Jens Neuse <jens.neuse@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
quick-js = { version = "0.3.0" }